services:
  - type: web
    name: ASL-CNN
    env: python
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
    startCommand: gunicorn app:app
